"""İlk Migrate

Revision ID: 354b691fbac3
Revises: 
Create Date: 2022-12-09 19:56:48.566111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '354b691fbac3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gonderiler', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tahminiteslimzamani', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('gonderiodemesekli', sa.String(), nullable=True))
        batch_op.drop_column('GonderiOdemeSekli')
        batch_op.drop_column('TahminiTeslimZamani')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gonderiler', schema=None) as batch_op:
        batch_op.add_column(sa.Column('TahminiTeslimZamani', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('GonderiOdemeSekli', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('gonderiodemesekli')
        batch_op.drop_column('tahminiteslimzamani')

    # ### end Alembic commands ###
